I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 316, in script
    add "explosion"
Exception: Sayer 'add' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 316, in script
    add "explosion"
  File "/Users/lily/Documents/Documents/dmgs/renpy-8.1.1-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/lily/Documents/Documents/dmgs/renpy-8.1.1-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'add' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.1.23060707
My Question 1.0
Sat May  4 19:10:36 2024
